### ISSUE TITLE
Change FirstName Property in tenant Model 

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#102]
lets change the FirstName property in the tenant Model to TenantFirstName. I think this will resolve https://github.com/mentorient/mentorient/issues/101

**Comment by drazenp** [comment]
If this PR https://github.com/mentorient/mentorient/pull/103 solve the problem with migrations we may not need anymore this issue.

**Comment by m-henderson** [comment]
@drazenp great job! I merged your PR and everything is working correctly.
