### ISSUE TITLE
Integrating KnockoutJS

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#108]
what do you all think about integrating knockout js into the  application? we could really start building nice flowing frontends.

**Comment by inthevortex** [comment]
I have worked with angular2/4 and its good and that kind of architecture has more portability.

**Comment by inthevortex** [comment]
Since you are also planning for an android and IOS app, why  not move the frontend to angular and the mvc will provide the backend along with APIs that will be called by all the three frontend applications.

**Comment by inthevortex** [comment]
you can close this issue.

**Comment by m-henderson** [comment]
@inthevortex closing now. Thanks!
