### ISSUE TITLE
Searching For Tenants

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#109]
Right now, on the tenants page, this is what is returned when you search for a tenant but they dont exist: 
![image](https://user-images.githubusercontent.com/16070192/35625635-af5548ba-0658-11e8-868a-b0708c01616c.png)
as you can see in the url, i am searching for a tenant, in this case her name is alyssa. I dont have any tenants named alyssa so it returns an alert that says hold up you dont have any tenants. 

we need to make it to where it says "no tenants found". 

keep in mind that we still want that alert to show if there are no tenants in the database at all.

**Comment by inthevortex** [comment]
Has this issue been solved?

**Comment by drazenp** [comment]
I think it is. @m-henderson?

**Comment by inthevortex** [comment]
I tested it. It has been solved. Kindly close the issue.

**Comment by m-henderson** [comment]
@inthevortex @drazenp thanks guys! I will go ahead and close this one
