### ISSUE TITLE
Profile image is deleted if profile saved without image

### ISSUE THREAD

**Issue by drazenp** [mentorient/mentorient#111]
Steps to reproduce:
- Log in the application
- Click on your name in the header (edit profile page)
- Select image and click Save. -> Image will appear in the header.
- Click again on the Save button. -> Image will disappear and error image will be shown.

**Comment by Hameds** [comment]
I will look into it

**Comment by Hameds** [comment]
It was a silly mistake! I fixed it in PR #116
