### ISSUE TITLE
SendGrid API key Not Importing from appsettings.json

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#117]
This past weekend, I made it to where all of the users that register have to click an activation link in their email. Well, I pushed the code into production and something went wrong ( i know what the problem was, i just dont have time to go into detail). 

Right now, the activation links are not being sent to the users that register because we are not importing the SendGridAPI key from appsettings.json correctly. 

Below is my attempt to pull in the API key from appsettings.json but it doesn't work for some reason:

https://github.com/mentorient/mentorient/blob/fc2d70175a83f4979399ccf2675db058041421cf/mentorient/Services/EmailSender.cs#L20

Our main goal is to read a sendgrid api key from appsettings.json. In order to test this, you can go to sendgrid and create you an API key. 

more discussion here: https://gitter.im/mentorient/Lobby

**Comment by inthevortex** [comment]
Ya, I didn't get my confirmation mail. The appsettings.json doesn't have any such field and why do we need to get it from environment variable?

**Comment by m-henderson** [comment]
@inthevortex the goal is to edit the appsettings.json so we can pull in the send grid config.

**Comment by inthevortex** [comment]
@m-henderson we can either put the key in appsettings.json and pull it using configuration manager or we can set it as the environment variable and pull that config. But to put it in the environment variable for testing and development, we would need to keep it somewhere so that people are able to obtain it.

**Comment by m-henderson** [comment]
@inthevortex let's put it in appsettings.json for now. I think this will get us going !

**Comment by inthevortex** [comment]
@m-henderson yes that will be the best idea. Please update the appsettings.json.

**Comment by inthevortex** [comment]
But that is for production usage, we can put a true in code for dev environment, so that it doesn't ask for verification.
