### ISSUE TITLE
Bearer token

### ISSUE THREAD

**Issue by drazenp** [mentorient/mentorient#121]
There is PR with implementation of authentication with Bearer token #120.
We can be used to access data from andoroid and iOS applications. I'm not sure if this make sense @m-henderson?

There is the API to generate the token and API to test it.
To test create post request on `http://[localhost:port]/api/token` with JSON data `{"email":"email@d.com", "password": "pass"}`. This API endpoint will return token. The token should be used to access protected API endpoint e.g. `http://[localhost:port]/api/Accounting` by adding header in the request like `Bearer somelongtokenstring`.

**Comment by drazenp** [comment]
If this is ok, before going on prod we could add secret key as environment variable.

**Comment by m-henderson** [comment]
@drazenp this looks like it makes sense. I will have to read up on the docs and test this locally; at least we are moving forward!

**Comment by inthevortex** [comment]
If the web interface is moved to angular, this will come in handy there too

**Comment by drazenp** [comment]
Sorry, wrong button :)

**Comment by drazenp** [comment]
PR #120 is merged, closing the ticket.
