### ISSUE TITLE
Change Destination of Contact Link

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#19]
Right now, the about link in the navigation bar redirects the user to https://mentorient-as.azurewebsites.net/Tenants 

But, it needs to redirect to https://mentorient-as.azurewebsites.net/Contact

**Comment by rembrandtreyes** [comment]
Is this still up for grabs?

**Comment by m-henderson** [comment]
@rembrandtreyes this was actually fixed in PR https://github.com/mentorient/mentorient/pull/24 . Sorry about that. Please have a look at some of the other issues and feel free to let me know if you have questions! 

Aldo, don't hesitate to create an issue yourself. 

cheers 🙂
