### ISSUE TITLE
Edit "New Tenant" Form

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#22]
The user of the application shoudl be able to type in the address of a tenant when adding a new tenant to the application. In the future, we are going to have multiple input fields, but I like to do it one at a time to keep things smooth. If you all have any suggestions, feel free to let us know.

**Comment by rembrandtreyes** [comment]
Maybe we can close this ticket since the form has been updated from other issues

**Comment by m-henderson** [comment]
Thanks. I will go ahead and close.
