### ISSUE TITLE
New Tenant Form Vlidation

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#46]
The new tenant form doesn't have client side validation. We need to validate that the data input into the form to insure satisfies the validation requirements using jquery before it makes a round trip to the server. . In aspnet core, the validation is handled through data attributes which already import the jquery. All you have to do is add the data attributes to the model. we do this  in pr https://github.com/mentorient/mentorient/pull/45 , But the form errors are not being displayed to the user because we have to add the asp-validation-for attributes as well as the asp-validation-summary attribute to the form.

**Comment by rembrandtreyes** [comment]
I'll work on this while I wait on the setup of the Issue #43

**Comment by m-henderson** [comment]
@rembrandtreyes sounds good 👍

**Comment by rembrandtreyes** [comment]
@m-henderson For the form validation. Did you want the phone number to take in a value of int? Becuase every time I try to run validation it states that it is out of the int bounds.  When I convert the variable to a string it then states that the SQL column only excepts int values. I think if we change the SQL column to except varchar it will allow me to pass the phone number through validation.

**Comment by m-henderson** [comment]
@rembrandtreyes good point. let's go ahead and change that to a string. could you open up an issue about this? 

If you dont feel comfortable fixing it, I will tackle it in about 30 minutes 👍

**Comment by rembrandtreyes** [comment]
Form validation is complete just need to change the data type of phone number

**Comment by m-henderson** [comment]
Awesome, I will work on this asap. I will keep you updated.

**Comment by rembrandtreyes** [comment]
This ticket can be closed as well.

**Comment by m-henderson** [comment]
Thanks, I will go ahead and close this one too.
