### ISSUE TITLE
Easy Fix For The Home Page

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#58]
at the bottom of the homepage are three tabs located to the left of the contact form. We need to put some text in the Free Updates and Community Driven Tab.

**Comment by rembrandtreyes** [comment]
@m-henderson Made some changes to the home page with my PR #72 . Don't know why my old commits are on that PR but it should interfere since it was the last PR. 

Unless you think it might mess with something.

**Comment by rembrandtreyes** [comment]
We can close this issue.

**Comment by m-henderson** [comment]
@rembrandtreyes thanks for the update. I am closing now.
