### ISSUE TITLE
Phone number SQL data type

### ISSUE THREAD

**Issue by rembrandtreyes** [mentorient/mentorient#68]
Whenever ever the for tries to pass in a phone number we get an error in the debugger. The error is caused by the phone number being a type int and the phone numbers are out of the range of int. Tried changing the data type to a string, but get another error in the debugger, this time it is because the data type on the back end only accepts integer for phone number and not a varchar.

**Comment by m-henderson** [comment]
@rembrandtreyes done.

**Comment by rembrandtreyes** [comment]
Nice!
