### ISSUE TITLE
Add firstname and Last name to application user

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#73]
lets add the first name and last name property to application user model so we can store the first and last name of the user.  

**warning**
I cant remember off the top of my head if the application user already has a column in the DB for firstname, i will have to check when I am able.

**Comment by drazenp** [comment]
Since the next task is to display first name, maybe it's wort adding the first name as a claim to avoid reading from db on each page load?

**Comment by m-henderson** [comment]
@drazenp Interesting. I think this is a good point and we could definitely do it this way.
