### ISSUE TITLE
Caruosel on home page

### ISSUE THREAD

**Issue by rembrandtreyes** [mentorient/mentorient#77]
### Expected Behavior
Would like to add a Carousel in place of the jumbotron and have the Carousel auto cycle through the different tabs

### Actual Behavior
Currently, the home page has a plain jumbotron that does not have much styling done.

### Steps to change home page
Going to implement a carousel on the homepage
Make changes to the style and design of the home page using bootstrap
Add more text and information on the homepage

**Comment by rembrandtreyes** [comment]
Added Carousel to home page

**Comment by m-henderson** [comment]
@rembrandtreyes go to mentorient.com and look at the carousel. is it showing wrong images?

**Comment by rembrandtreyes** [comment]
Yeah, I forgot to mention I just chose the stock photos that came with the project as placeholders. I was going to update the photos in the next design iteration of the home page.

**Comment by m-henderson** [comment]
No problem!
