### ISSUE TITLE
New Accounting Entry Form  (Easy fix)

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#79]
when clicking the cancel button on the new accounting entry form, it does not take you back to the account list; it does nothing. We need to wire the button up so the user can cancel the creation of a new accounting entry.

**Comment by rembrandtreyes** [comment]
I'll try and do something with this today.

**Comment by m-henderson** [comment]
thanks @rembrandtreyes

**Comment by m-henderson** [comment]
this is now working. I am going to go ahead and close.
